"""adds planet model

Revision ID: 691873bc89a9
Revises: fcb077a5ff81
Create Date: 2024-10-31 16:13:38.411024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691873bc89a9'
down_revision = 'fcb077a5ff81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('distance_from_sun', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    # ### end Alembic commands ###
